package com.github.rabidfish.example1

import com.github.rabidfish.Number;

rule "Stateless Simple Example Less Than 5"
	when
        number : Number( number.value < 5 )

	then
		System.out.println( "Value is less than 5" );
	
end

rule "Stateless Simple Example Equal to 5"
	when
        number : Number( number.value == 5 )

	then
        System.out.println( "Value is equal to 5" );
	
end

rule "Stateless Simple Example More Than 5"
	when
        number : Number( number.value > 5 )

	then
        System.out.println( "Value is more than 5" );
	
end
