package com.github.rabid_fish.example2

import com.github.rabid_fish.Number;

rule "Stateless List Example Less Than 5"
	when
        number : Number( number.value < 5 )

	then
		number.setMessage( "Value is less than 5" );
	
end

rule "Stateless List Example Equal to 5"
	when
        number : Number( number.value == 5 )

	then
        number.setMessage( "Value is equal to 5" );
	
end

rule "Stateless List Example More Than 5"
	when
        number : Number( number.value > 5 )

	then
        number.setMessage( "Value is more than 5" );
	
end
