package com.github.rabid_fish.example2

import com.github.rabid_fish.MathResult;

rule "Stateless List Example Less Than 5"
	when
        result : MathResult( result.value < 5 )

	then
		result.setMessage( "Value is less than 5" );
	
end

rule "Stateless List Example Equal to 5"
	when
        result : MathResult( result.value == 5 )

	then
        result.setMessage( "Value is equal to 5" );
	
end

rule "Stateless List Example More Than 5"
	when
        result : MathResult( result.value > 5 )

	then
        result.setMessage( "Value is more than 5" );
	
end
