package com.github.rabid_fish.example1

import rabid_fish.github.com.exampledroolsandjaxb.ContactType;

rule "High risk group male"
	when
        contact : ContactType( age < 21, gender == "male" )

	then
		contact.setRisk("High");
	
end

rule "Medium risk group male"
	when
        contact : ContactType( age <= 25, age >= 21, gender == "male" )

	then
		contact.setRisk("Medium");
		
end

rule "High risk group female"
	when
        contact : ContactType( age < 18, gender == "female" )

	then
		contact.setRisk("High");
	
end

rule "Medium risk group female"
	when
        contact : ContactType( age <= 25, age >= 18, gender == "female" )

	then
		contact.setRisk("Medium");
		
end

rule "Low risk group"
	when
        contact : ContactType( age > 25 )

	then
		contact.setRisk("Low");

end
