package com.github.rabid_fish.example1

import com.github.rabid_fish.MathResult;

rule "Stateless Simple Example Less Than 5"
	when
        result : MathResult( result.value < 5 )

	then
		System.out.println( "Value is less than 5" );
	
end

rule "Stateless Simple Example Equal to 5"
	when
        result : MathResult( result.value == 5 )

	then
        System.out.println( "Value is equal to 5" );
	
end

rule "Stateless Simple Example More Than 5"
	when
        result : MathResult( result.value > 5 )

	then
        System.out.println( "Value is more than 5" );
	
end
