package com.github.rabidfish.example1

import https.github_com.rabidfish.ContactType;
import com.github.rabidfish.Number;

rule "High risk group male even"
	when
        contact : ContactType( age < 21, gender == "male" )
		number : Number(even == "true")
		
	then
		contact.setRisk("High Even");
	
end

rule "High risk group male odd"
	when
        contact : ContactType( age < 21, gender == "male" )
		number : Number(even == "false")
		
	then
		contact.setRisk("High Odd");
	
end

rule "Medium risk group male even"
	when
        contact : ContactType( age <= 25, age >= 21, gender == "male" )
		number : Number(even == "true")

	then
		contact.setRisk("Medium Even");
		
end

rule "Medium risk group male odd"
	when
        contact : ContactType( age <= 25, age >= 21, gender == "male" )
		number : Number(even == "false")

	then
		contact.setRisk("Medium Odd");
		
end

rule "High risk group female even"
	when
        contact : ContactType( age < 18, gender == "female" )
		number : Number(even == "true")

	then
		contact.setRisk("High Even");
	
end

rule "High risk group female odd"
	when
        contact : ContactType( age < 18, gender == "female" )
		number : Number(even == "false")

	then
		contact.setRisk("High Odd");
	
end

rule "Medium risk group female even"
	when
        contact : ContactType( age <= 25, age >= 18, gender == "female" )
		number : Number(even == "true")

	then
		contact.setRisk("Medium Even");
		
end

rule "Medium risk group female odd"
	when
        contact : ContactType( age <= 25, age >= 18, gender == "female" )
		number : Number(even == "false")

	then
		contact.setRisk("Medium Odd");
		
end

rule "Low risk group"
	when
        contact : ContactType( age > 25 )

	then
		contact.setRisk("Low");

end
